[package]
name = "js-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.79"
console_error_panic_hook = "0.1.7"
fluvio-wasm-timer = "0.2.5"

[dependencies.web-sys]
version = "0.3.56"
features = ["Window"]