[package]
name = "js-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.80"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.57"
features = [
    "Window",
    "Document",
    "HtmlElement",
]
