[package]
name = "js-utils"
version = "0.1.0"
edition = "2021"

[features]
default = ["panic_hook"]
panic_hook = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.82"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dependencies.web-sys]
version = "0.3.59"
features = [
    "Window",
    "Document",
    "HtmlElement",
]
